<a href="https://colab.research.google.com/github/swhacademy/tensorflow-guide/blob/master/0_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 참고 사이트


*   https://docs.scipy.org/doc/numpy-1.16.0/user/basics.types.html
*   https://datascienceschool.net
*   http://taewan.kim/post/numpy_cheat_sheet


# numpy

- Python의 과학 컴퓨팅을 위한 핵심 라이브러리
- 고성능 다차원 배열 객체와 이러한 배열 작업을위한 도구를 제공

## Array 배열
- 속도가 느리고 메모리를 많이 차지하는 List의 대안
- 적은 메모리로 데이터를 빠르게 처리
- 모든 요소가 같은 자료형이며, 요소의 갯수를 바꿀 수 없다.
- 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용

## numpy 모듈

In [0]:
import numpy as np
np.__version__

'1.16.2'

## ndarray 특징


*   NumPy 배열의 구조는 “Shape“으로 표현. Shape은 배열의 구조를 파이썬 튜플 자료형을 이용하여 정의



In [0]:
a = np.array([1, 2, 3]) # rank = 1
print(type(a)) # ndarrayd은 N-dimensional Array의 약자
print(a.ndim) # 배열의 차원(Rank)
print(a.shape) # 배열의 크기
print(a.dtype) # 배열의 자료형

<class 'numpy.ndarray'>
1
(3,)
int64


### ndarray 자료형

| dtype 접두사 | 설명 |
|---|---|---|
| b | boolean  |
| i | 정수  |
| u | 부호 없는 정수  |
| f | 부동소수점  |
| c | 복소 부동소수점  |
| O | 객체  |
| S | 바이트 문자열  |
| U | 유니코드 문자열  |

## 배열 만들기

*   리스트를 통해 배열생성
*   데이터을 자동으로 얻은 후 배열생성
*   난수을 통해 배열생성

### 리스트를 통해 배열생성

In [0]:
a = np.array([1, 2, 3], dtype='f') # dtype이 없으면 값을 보고 판단
print(a)
print(a.dtype)

a = [1, 2, 3]
b = np.array(a)
print(b)

a = [[1, 2, 3], [4, 5, 6]]
b = np.array(a)  # 2 x 3 배열
print(b)

a = [
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]], 
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
]
b = np.array(a)  # 4 * 2 x 3 배열
print(b)

[1. 2. 3.]
float32
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 데이터을 자동으로 얻은 후 배열생성

#### zeros
- 표현 : zeros(배열의 크기, dtype='f')
- 값을 0, 문자열인 경우에는 비어있는 값을 배열로 얻을 때 사용

#### zeros_like
- 표현 : zeros_like(다른 배열, dtype='f')
- zeros 유사, 배열의 크기를 명시하지 않고 다른 배열과 같은 크기로 생성

In [0]:
a = np.zeros(5) # 값이 0인 배열생성, dtype을 지정하지 않으면 초기값은 float
print(a)

a = np.zeros((2, 3)) # 값이 0인 이차원 배열생성
print(a)

a = np.zeros((3, 2), dtype="i") # 값이 0인 정수형 이차원 배열생성
print(a)

a = np.zeros(5, dtype="U") # 비어있는 문자열형 배열생성
print(a)

b = np.zeros_like(a, dtype='f') # dtype생략 시, a값을 통해 자료형을 판단
print(b)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]]
['' '' '' '' '']
[0. 0. 0. 0. 0.]


#### ones
- 표현 : ones(배열의 크기, dtype='f')
- 1로 초기화된 배열을 얻을 때 사용

#### ones_like
- 표현 : ones_like(다른 배열, dtype='f')
- ones과 유사, 배열의 크기를 명시하지 않고 다른 배열과 같은 크기로 생성

In [0]:
a = np.ones((2, 3, 4), dtype="i") # 배열의 크기를 튜플로 명시
print(a)

b = np.ones_like(a, dtype="f") # dtype생략 시, a값을 통해 자료형을 판단
print(b)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


#### empty
- 배열을 생성만 하고 값을 초기화하지 않은 형태
- 배열의 크기가 커지면 초기화하는데 시간이 걸리기 때문에 사용

In [24]:
a = np.empty((2, 3))
print(a)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


#### arange
- numpy버전의 range

In [0]:
a = np.arange(5)
print(a)

a = np.arange(3, 15, 2)  # 시작, 끝(포함하지 않음), 단계
print(a)

[0 1 2 3 4]
[ 3  5  7  9 11 13]


#### linspace, logspace
- 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할

In [0]:
a = np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수
print(a)

a = np.logspace(0.1, 1, 10)
print(a)

[  0.  25.  50.  75. 100.]
[ 1.25892541  1.58489319  1.99526231  2.51188643  3.16227766  3.98107171
  5.01187234  6.30957344  7.94328235 10.        ]


### 난수을 통해 배열생성

![평균, 분산, 표준편차](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory&fname=http%3A%2F%2Fcfile3.uf.tistory.com%2Fimage%2F276E5D47566A1CA3295C43)



> https://learnx.tistory.com

#### random.normal


*   normal(loc=0.0, scale=1.0, size=None)
*   정규 분포 확률 밀도에서 표본 추출
*   loc: 정규 분포의 평균
*   scale: 표준편차

In [0]:
a = np.random.normal(1, 1, 10)
a                     

array([0.38992151, 1.47401165, 0.78675786, 0.4985589 , 2.33245781,
       1.72024418, 0.23102113, 1.72533903, 0.36422755, 1.01989448])

#### random.rand


*   rand(shape=None)
*   Shape에 맞는 배열 생성 후 난수로 초기화
*   난수의 구간은 0이상 1미만

In [0]:
a = np.random.rand(10)
print(a)
b = np.random.rand(3, 2)
print(b)

[0.78124097 0.99959665 0.46560599 0.68541673 0.81418588 0.44873984
 0.59769365 0.08633434 0.14985837 0.89396077]
[[0.75010616 0.77332283]
 [0.20008004 0.0814754 ]
 [0.23709364 0.4057705 ]]


#### 약속된 난수 (seed)

In [0]:
# seed 값을 설정
np.random.seed(100)

for b in range(2):
  a = np.random.random((2, 2))
  print(a)

# 같은 seed값을 가진 난수를 아래에서 반복
np.random.seed(100)

for b in range(2):
  a = np.random.random((2, 2))
  print(a)

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]
[[0.00471886 0.12156912]
 [0.67074908 0.82585276]]
[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]
[[0.00471886 0.12156912]
 [0.67074908 0.82585276]]


##  벡터화 연산
- 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리

In [0]:
# List인 경우,
a = [1, 2, 3]
c = []
for b in a:
    c.append(2 * b)
print(c)
print(a * 2)

[2, 4, 6]
[1, 2, 3, 1, 2, 3]


In [0]:
# Array인 경우,
a = [1, 2, 3]
b = np.array(a)
c = b * 2
print(c)
print(c[2])

[2 4 6]
6


In [0]:
# 산술 연산 뿐만 아니라, 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용
a = np.array([1, 2, 3])
# b = np.array([10, 20]) # Shape가 동일해야 가능
b = np.array([10, 20, 30])
c = 2 * a + b
print(c)
print(c / 2)
print(a == 2)
print(a > 2)
print(0 == (b % 10))

[12 24 36]
[ 6. 12. 18.]
[False  True False]
[False False  True]
[ True  True  True]


## 인덱싱

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a[0])
print(a[0,1]) # 첫 번째 행의 두 번째 열
print(a[0,-1]) # 첫 번째 행의 마지막 열
print(len(a), len(a[0])) # 행, 열의 갯수

[[1 2 3]
 [4 5 6]]
[1 2 3]
2
3
2 3


##### 🔍 문제
- 위의 `a = np.array([[1, 2, 3], [4, 5, 6]])`로부터 이차원 배열 전체 요소을 아래와 같이 출력

1 2 3 4 5 6 

<details>
  <summary>Solution!</summary>
  
<pre>
a = np.array([[1, 2, 3], [4, 5, 6]])
for b in range(len(a)):
    for c in range(len(a[b])):
        print(a[b, c], end=" ")
</pre>
</details>

## 슬라이싱

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, :]) # 첫 번째 행의 모든 열
print(a[1, 1:]) # 두 번째 행의 두 번째 열부터 끝까지
print(a[:, :2]) # 모든 행의 첫 번째 열부터 두 번째 열까지

[1 2 3]
[5 6]
[[1 2]
 [4 5]]


##### 🔍 문제
- 반복을 사용하여 아래의 리스트를 만든다.
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]]
- `Array`을 사용하여 16을 인덱싱한다.
- `Array`을 사용하여 [7, 8]을 슬라이싱 한다. 

<details>
  <summary>Solution!</summary>
  
<pre>
a = []
b = []
for c in range(1, 21):
    b.append(c)
    if c % 4 == 0:
        a.append(b)
        b = []
print(a)
d = np.array(a)
print(d[3][-1])
print(d[1, 2:])
</pre>
</details>

## 배열 인덱싱
- 대괄호안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 배열(인덱스 배열)을 넣는 경우
- 인덱스 배열에는 Boolean배열방식, 정수형 배열방식이 있다.
 - Boolean배열방식은 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같다.
 - 정수형 배열방식은 인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가리키는 인덱스 정수

In [0]:
a = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [0]:
# Boolean형 배열방식
b = np.array([True, False, True, False, True,
                False, True, False, True, False])
print(a[b])
print(a % 2)
print(a % 2 == 0)
print(a[a % 2 == 0])

[10 12 14 16 18]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[10 12 14 16 18]


In [0]:
# 정수형 배열방식
c = np.array([1, 3, 5, 7, 9])
d = np.array([1, 1, 0, 0, 4, 4, 1, 1, 1, 1, 1, 1, 1]) # 배열 인덱스가 원래의 배열보다 클 수 있다.
print(a[c])
print(a[d])

[11 13 15 17 19]
[11 11 10 10 14 14 11 11 11 11 11 11 11]


In [0]:
# 배열 인덱싱은 다차원 배열의 각 차원에 대해서도 가능
e= np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a[e])
print(e[:, [True, False, False, True]])

[[11 12 13 14]
 [15 16 17 18]]
[[1 4]
 [5 8]]


##### 🔍 문제
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

- 이 배열에서 3의 배수를 찾아라.
- 이 배열에서 3으로 나누면 나누어지고 4로 나누면 2가 남는 수를 찾아라.

<details>
  <summary>Solution!</summary>
  
<pre>
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(z[z % 3 == 0])
print(z[(z % 3 == 0) & (z % 4 == 2)])
</pre>
</details>

## 연산
- +, -, *, / 등의 연산자를 사용
- add(), substract(), multiply(), divide() 등의 함수를 사용

In [0]:
a = np.array([1,2])
b = np.array([3,4])
 
# 각 요소 더하기
c = a + b
# c = np.add(a, b)
print(c)
 
# 각 요소 빼기
c = a - b
# c = np.subtract(a, b)
print(c)
 
# 각 요소 곱하기
# c = a * b
c = np.multiply(a, b)
print(c)
 
# 각 요소 나누기
# c = a / b
c = np.divide(a, b)
print(c)

[4 6]
[-2 -2]
[3 8]
[0.33333333 0.5       ]


In [0]:
# vector와 matrix의 product을 연산
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]


In [0]:
a = np.array([[1,2],[3,4]])
s = np.sum(a)
print(s)   # 각 요소의 합
 
# axis=0 이면, 컬럼끼리 더함
# axis=1 이면, 행끼리 더함
s = np.sum(a, axis=0)
print(s)
s = np.sum(a, axis=1)
print(s)

s = np.prod(a)
print(s)   # 각 요소의 곱

10
[4 6]
[3 7]
24
